# Pilot content: shape S02 - one continuous variable, split by group
ENTRIES = [
 dict(id='P004', slug='box', name='Box-and-whisker plot', alias='box plot · Tukey box plot',
  tier='universal', depth='deep',
  defn="A five-number summary drawn as a rectangle: quartiles, median, and whiskers reaching the most extreme point within 1.5 × IQR.",
  read=["Box is the middle half of the data; the line is the median",
        "A median off-centre in its box means skew",
        "Whiskers stop at a rule, not at the range",
        "Points past the whiskers are drawn individually"],
  hides=["Modality — a bimodal group can draw the same box as a unimodal one",
         "Sample size — n = 6 and n = 6000 look identical",
         "Every individual observation"],
  use=["Many groups at once, where space is tight",
       "Distributions already confirmed unimodal"],
  avoid=["Groups that may contain subpopulations",
         "Fewer than about ten observations per group",
         "Data you have not first plotted raw"],
  r="ggplot(d, aes(group, value)) + geom_boxplot()",
  py="seaborn.boxplot(data=d, x='group', y='value')",
  caps=dict(shape='no', n='no', raw='no', out='yes', small='partial', large='yes')),

 dict(id='P005', slug='notched-box', name='Notched box plot', alias='',
  tier='domain-signature', depth='standard',
  defn="A box plot with a wedge cut around the median spanning roughly ±1.58 × IQR / √n — an approximate 95% interval for the median.",
  read=["Non-overlapping notches mean medians differ at about the 5% level",
        "The notch narrows as n grows",
        "A notch folding outside the box means the interval exceeds the IQR"],
  hides=["Everything a plain box plot hides",
         "Sample size, except indirectly through notch width"],
  use=["Letting the eye do the comparison between medians",
       "Unimodal groups of moderate size"],
  avoid=["Small n, where the folding artefact appears",
         "Audiences who read overlap as proof of no difference"],
  r="ggplot(d, aes(group, value)) + geom_boxplot(notch = TRUE)",
  py="seaborn.boxplot(data=d, x='group', y='value', notch=True)",
  caps=dict(shape='no', n='partial', raw='no', out='yes', small='partial', large='yes')),

 dict(id='P006', slug='letter-value', name='Letter-value plot', alias='boxen plot',
  tier='niche', depth='stub',
  defn="A box plot extended inward — quartiles, then eighths, then sixteenths, each a narrower box, stopping when the estimate becomes unreliable.",
  read=["Each nested rectangle halves the tail probability",
        "Wide nesting means heavy tails",
        "Boxes that shrink fast mean a concentrated distribution"],
  hides=["Modality, like the box plot",
         "Individual observations"],
  use=["Samples in the thousands, where tail shape matters",
       "Replacing the outlier spray a box plot produces at large n"],
  avoid=["Small samples — the deep letter values have nothing to estimate from"],
  r="ggplot(d, aes(group, value)) + lvplot::geom_lv()",
  py="seaborn.boxenplot(data=d, x='group', y='value')",
  caps=dict(shape='partial', n='no', raw='no', out='yes', small='no', large='yes')),

 dict(id='P007', slug='violin', name='Violin plot', alias='',
  tier='universal', depth='deep',
  defn="A kernel density estimate mirrored about its axis, so width at any height is proportional to the estimated density there.",
  read=["Width is frequency",
        "One bulge is unimodal; a waist between two is a split population",
        "The tapering ends are the kernel, not the data"],
  hides=["Sample size — six observations render as a smooth population",
         "That the bandwidth is a choice: widen it and the waist disappears"],
  use=["Comparing shape across groups with roughly thirty or more each"],
  avoid=["Small n, unless the raw points are drawn over it",
         "Any context where it will be read as raw data — it is a model"],
  r="ggplot(d, aes(group, value)) + geom_violin()",
  py="seaborn.violinplot(data=d, x='group', y='value')",
  caps=dict(shape='yes', n='no', raw='no', out='no', small='no', large='yes')),

 dict(id='P008', slug='bean', name='Bean plot', alias='',
  tier='domain-signature', depth='standard',
  defn="A violin outline with every observation drawn inside it as a short horizontal line, plus a bar at the group mean.",
  read=["The outline gives shape, the internal lines give the observations",
        "Line density reveals the true sample size",
        "A solid band means repeated values"],
  hides=["Little — it spends width instead of hiding things"],
  use=["Small to moderate groups where the width is available"],
  avoid=["Beyond about a hundred per group, where the lines merge into a block"],
  r="beanplot::beanplot(value ~ group, data = d)",
  py="# no direct equivalent; compose violinplot + eventplot",
  caps=dict(shape='yes', n='yes', raw='yes', out='yes', small='yes', large='no')),

 dict(id='P009', slug='sina', name='Sina plot', alias='',
  tier='domain-signature', depth='standard',
  defn="Points jittered horizontally, with the jitter width at each height set by the local density — a violin's silhouette made of real observations.",
  read=["Read the shape as you would a violin",
        "Every mark is one observation",
        "Width and point concentration reinforce each other"],
  hides=["Very little — with no area fill it cannot fabricate density from few points"],
  use=["Almost anywhere you were about to draw a violin under a few hundred points",
       "Often the better default"],
  avoid=["Very large n, where the points saturate the available width"],
  r="ggplot(d, aes(group, value)) + ggforce::geom_sina()",
  py="# closest: seaborn.violinplot(inner='point'), or ptitprince",
  caps=dict(shape='yes', n='yes', raw='yes', out='yes', small='yes', large='partial')),

 dict(id='P010', slug='raincloud', name='Raincloud plot', alias='',
  tier='universal', depth='deep',
  defn="Three marks in one lane — a half violin for shape, a narrow box for the summary statistics, and jittered raw points beneath.",
  read=["Points: what was measured, and how much of it",
        "Box: the summary you would quote",
        "Half violin: the shape",
        "Where the three disagree is the finding"],
  hides=["Almost nothing — its cost is horizontal space, not information"],
  use=["When the distribution is the result rather than a nuisance",
       "Six groups or fewer"],
  avoid=["Many groups, small multiples, or column-width printing"],
  r="ggplot(d, aes(group, value)) + ggrain::geom_rain()",
  py="ptitprince.RainCloud(data=d, x='group', y='value')",
  caps=dict(shape='yes', n='yes', raw='yes', out='yes', small='yes', large='partial')),

 dict(id='P011', slug='strip', name='Strip plot', alias='jitter plot · dot strip',
  tier='universal', depth='deep',
  defn="Every observation plotted against its group, displaced horizontally at random so that coincident values separate.",
  read=["Count the marks",
        "Density of ink is density of data",
        "Nothing has been summarised, estimated or smoothed"],
  hides=["Nothing — but overplotting breaks the ink-to-count relationship at high n",
         "The jitter is random, so the figure changes on every run"],
  use=["Small groups",
       "As an overlay beneath a box or violin, to keep the summary honest"],
  avoid=["Large n on its own",
         "Publishing without a fixed random seed"],
  r="ggplot(d, aes(group, value)) + geom_jitter(width = 0.2)",
  py="seaborn.stripplot(data=d, x='group', y='value', jitter=0.2)",
  caps=dict(shape='partial', n='yes', raw='yes', out='yes', small='yes', large='no')),

 dict(id='P012', slug='wilkinson-dot', name='Wilkinson dot plot', alias='',
  tier='universal', depth='deep',
  defn="Values binned and drawn as one fixed-size dot per observation, stacked outward, so stack height is a count.",
  read=["Each dot is exactly one observation",
        "You can count the sample size off the page",
        "The envelope is a histogram made of its constituents"],
  hides=["Nothing at small n",
         "Bin width is a choice carrying the same risk as in a histogram"],
  use=["Teaching, and small clinical series",
       "Any figure where a reader should be able to verify n by eye"],
  avoid=["Large samples — the stacks run off the plot"],
  r="ggplot(d, aes(group, value)) + geom_dotplot(binaxis = 'y', stackdir = 'center')",
  py="# no direct equivalent; bin then scatter, or plotnine's geom_dotplot",
  caps=dict(shape='yes', n='yes', raw='yes', out='yes', small='yes', large='no')),

 dict(id='P013', slug='beeswarm', name='Beeswarm plot', alias='swarm plot',
  tier='universal', depth='deep',
  defn="Every observation plotted, offset deterministically rather than randomly — packed sideways just far enough to avoid overlapping its neighbours.",
  read=["The outline is a density estimate you can count",
        "Reproducible, unlike a strip plot",
        "Every unit of width is an actual observation"],
  hides=["Nothing, until the swarm reaches the width it is allowed",
         "Past that limit it compresses or overlaps silently — roughly a few hundred per group"],
  use=["The default for showing raw values across groups at moderate n",
       "Standard in immunology and cell biology figure panels"],
  avoid=["Groups in the thousands",
         "Libraries that do not warn when the swarm overflows"],
  r="ggplot(d, aes(group, value)) + ggbeeswarm::geom_beeswarm()",
  py="seaborn.swarmplot(data=d, x='group', y='value')",
  caps=dict(shape='yes', n='yes', raw='yes', out='yes', small='yes', large='no')),

 dict(id='P321', slug='stacked-violin', name='Stacked violin plot', alias='',
  tier='niche', depth='stub',
  defn="A single-cell convention: one narrow row of violins per gene over a shared cluster axis, stacked so marker patterns read as a grid.",
  read=["Across a row: where a gene is expressed",
        "Down a column: what defines a cluster",
        "One tall violin in a row is a clean marker"],
  hides=["Absolute expression — rows are scaled independently",
         "Dropout — mass at zero mixes true absence with capture failure"],
  use=["Presenting marker genes for annotated clusters"],
  avoid=["Any claim comparing quantity between one gene and another"],
  r="Seurat::VlnPlot(obj, features = genes, stack = TRUE)",
  py="scanpy.pl.stacked_violin(adata, genes, groupby='cluster')",
  caps=dict(shape='yes', n='no', raw='no', out='no', small='no', large='yes')),

 dict(id='P322', slug='qc-violin', name='QC violin panel', alias='nFeature / nCount / percent.mt plot',
  tier='niche', depth='stub',
  defn="The standard opening figure of a single-cell analysis: genes, counts and mitochondrial fraction per cell, with candidate filter thresholds drawn on.",
  read=["Read the tail, not the bulk",
        "A long upper tail in counts suggests doublets",
        "A high mitochondrial fraction suggests dying cells",
        "The threshold lines are the decision the figure exists to support"],
  hides=["Each metric alone — cells that are only jointly anomalous stay invisible"],
  use=["Choosing and documenting QC cutoffs before filtering",
       "Pair it with counts against mitochondrial fraction"],
  avoid=["Treating defaults as universal — thresholds vary by tissue and chemistry"],
  r="Seurat::VlnPlot(obj, features = c('nFeature_RNA','nCount_RNA','percent.mt'))",
  py="scanpy.pl.violin(adata, ['n_genes_by_counts','total_counts','pct_counts_mt'])",
  caps=dict(shape='yes', n='no', raw='partial', out='yes', small='no', large='yes')),
]
CAPCOLS=[('shape','Distribution shape'),('n','Sample size'),('raw','Individual points'),
         ('out','Outliers'),('small','Honest at small n'),('large','Scales past 1000')]
