# Pilot content: shape S02 - one continuous variable, split by group
ENTRIES = [
 dict(id='P004', slug='box', name='Box-and-whisker plot', alias='box plot · Tukey box plot',
  tier='universal', depth='deep',
  defn="A five-number summary drawn as a rectangle: quartiles, median, and whiskers reaching the most extreme point within 1.5 × IQR.",
  read=["Box is the middle half of the data; the line is the median",
        "A median off-centre in its box means skew",
        "Whiskers stop at a rule, not at the range",
        "Points past the whiskers are drawn individually"],
  hides=["Modality — a bimodal group can draw the same box as a unimodal one",
         "Sample size — n = 6 and n = 6000 look identical",
         "Every individual observation"],
  use=["Many groups at once, where space is tight",
       "Distributions already confirmed unimodal"],
  avoid=["Groups that may contain subpopulations",
         "Fewer than about ten observations per group",
         "Data you have not first plotted raw"],
  r="ggplot(d, aes(group, value)) + geom_boxplot()",
  py="seaborn.boxplot(data=d, x='group', y='value')",
  caps=dict(shape='no', n='no', raw='no', out='yes', small='partial', large='yes')),

 dict(id='P005', slug='notched-box', name='Notched box plot', alias='',
  tier='domain-signature', depth='standard',
  defn="A box plot with a wedge cut around the median spanning roughly ±1.58 × IQR / √n — an approximate 95% interval for the median.",
  read=["Non-overlapping notches mean medians differ at about the 5% level",
        "The notch narrows as n grows",
        "A notch folding outside the box means the interval exceeds the IQR"],
  hides=["Everything a plain box plot hides",
         "Sample size, except indirectly through notch width"],
  use=["Letting the eye do the comparison between medians",
       "Unimodal groups of moderate size"],
  avoid=["Small n, where the folding artefact appears",
         "Audiences who read overlap as proof of no difference"],
  r="ggplot(d, aes(group, value)) + geom_boxplot(notch = TRUE)",
  py="seaborn.boxplot(data=d, x='group', y='value', notch=True)",
  caps=dict(shape='no', n='partial', raw='no', out='yes', small='partial', large='yes')),

 dict(id='P006', slug='letter-value', name='Letter-value plot', alias='boxen plot',
  tier='niche', depth='stub',
  defn="A box plot extended inward — quartiles, then eighths, then sixteenths, each a narrower box, stopping when the estimate becomes unreliable.",
  read=["Each nested rectangle halves the tail probability",
        "Wide nesting means heavy tails",
        "Boxes that shrink fast mean a concentrated distribution"],
  hides=["Modality, like the box plot",
         "Individual observations"],
  use=["Samples in the thousands, where tail shape matters",
       "Replacing the outlier spray a box plot produces at large n"],
  avoid=["Small samples — the deep letter values have nothing to estimate from"],
  r="ggplot(d, aes(group, value)) + lvplot::geom_lv()",
  py="seaborn.boxenplot(data=d, x='group', y='value')",
  caps=dict(shape='partial', n='no', raw='no', out='yes', small='no', large='yes')),

 dict(id='P007', slug='violin', name='Violin plot', alias='',
  tier='universal', depth='deep',
  defn="A kernel density estimate mirrored about its axis, so width at any height is proportional to the estimated density there.",
  read=["Width is frequency",
        "One bulge is unimodal; a waist between two is a split population",
        "The tapering ends are the kernel, not the data"],
  hides=["Sample size — six observations render as a smooth population",
         "That the bandwidth is a choice: widen it and the waist disappears"],
  use=["Comparing shape across groups with roughly thirty or more each"],
  avoid=["Small n, unless the raw points are drawn over it",
         "Any context where it will be read as raw data — it is a model"],
  r="ggplot(d, aes(group, value)) + geom_violin()",
  py="seaborn.violinplot(data=d, x='group', y='value')",
  caps=dict(shape='yes', n='no', raw='no', out='no', small='no', large='yes')),

 dict(id='P008', slug='bean', name='Bean plot', alias='',
  tier='domain-signature', depth='standard',
  defn="A violin outline with every observation drawn inside it as a short horizontal line, plus a bar at the group mean.",
  read=["The outline gives shape, the internal lines give the observations",
        "Line density reveals the true sample size",
        "A solid band means repeated values"],
  hides=["Little — it spends width instead of hiding things"],
  use=["Small to moderate groups where the width is available"],
  avoid=["Beyond about a hundred per group, where the lines merge into a block"],
  r="beanplot::beanplot(value ~ group, data = d)",
  py="# no direct equivalent; compose violinplot + eventplot",
  caps=dict(shape='yes', n='yes', raw='yes', out='yes', small='yes', large='no')),

 dict(id='P009', slug='sina', name='Sina plot', alias='',
  tier='domain-signature', depth='standard',
  defn="Points jittered horizontally, with the jitter width at each height set by the local density — a violin's silhouette made of real observations.",
  read=["Read the shape as you would a violin",
        "Every mark is one observation",
        "Width and point concentration reinforce each other"],
  hides=["Very little — with no area fill it cannot fabricate density from few points"],
  use=["Almost anywhere you were about to draw a violin under a few hundred points",
       "Often the better default"],
  avoid=["Very large n, where the points saturate the available width"],
  r="ggplot(d, aes(group, value)) + ggforce::geom_sina()",
  py="# closest: seaborn.violinplot(inner='point'), or ptitprince",
  caps=dict(shape='yes', n='yes', raw='yes', out='yes', small='yes', large='partial')),

 dict(id='P010', slug='raincloud', name='Raincloud plot', alias='',
  tier='universal', depth='deep',
  defn="Three marks in one lane — a half violin for shape, a narrow box for the summary statistics, and jittered raw points beneath.",
  read=["Points: what was measured, and how much of it",
        "Box: the summary you would quote",
        "Half violin: the shape",
        "Where the three disagree is the finding"],
  hides=["Almost nothing — its cost is horizontal space, not information"],
  use=["When the distribution is the result rather than a nuisance",
       "Six groups or fewer"],
  avoid=["Many groups, small multiples, or column-width printing"],
  r="ggplot(d, aes(group, value)) + ggrain::geom_rain()",
  py="ptitprince.RainCloud(data=d, x='group', y='value')",
  caps=dict(shape='yes', n='yes', raw='yes', out='yes', small='yes', large='partial')),

 dict(id='P011', slug='strip', name='Strip plot', alias='jitter plot · dot strip',
  tier='universal', depth='deep',
  defn="Every observation plotted against its group, displaced horizontally at random so that coincident values separate.",
  read=["Count the marks",
        "Density of ink is density of data",
        "Nothing has been summarised, estimated or smoothed"],
  hides=["Nothing — but overplotting breaks the ink-to-count relationship at high n",
         "The jitter is random, so the figure changes on every run"],
  use=["Small groups",
       "As an overlay beneath a box or violin, to keep the summary honest"],
  avoid=["Large n on its own",
         "Publishing without a fixed random seed"],
  r="ggplot(d, aes(group, value)) + geom_jitter(width = 0.2)",
  py="seaborn.stripplot(data=d, x='group', y='value', jitter=0.2)",
  caps=dict(shape='partial', n='yes', raw='yes', out='yes', small='yes', large='no')),

 dict(id='P012', slug='wilkinson-dot', name='Wilkinson dot plot', alias='',
  tier='universal', depth='deep',
  defn="Values binned and drawn as one fixed-size dot per observation, stacked outward, so stack height is a count.",
  read=["Each dot is exactly one observation",
        "You can count the sample size off the page",
        "The envelope is a histogram made of its constituents"],
  hides=["Nothing at small n",
         "Bin width is a choice carrying the same risk as in a histogram"],
  use=["Teaching, and small clinical series",
       "Any figure where a reader should be able to verify n by eye"],
  avoid=["Large samples — the stacks run off the plot"],
  r="ggplot(d, aes(group, value)) + geom_dotplot(binaxis = 'y', stackdir = 'center')",
  py="# no direct equivalent; bin then scatter, or plotnine's geom_dotplot",
  caps=dict(shape='yes', n='yes', raw='yes', out='yes', small='yes', large='no')),

 dict(id='P013', slug='beeswarm', name='Beeswarm plot', alias='swarm plot',
  tier='universal', depth='deep',
  defn="Every observation plotted, offset deterministically rather than randomly — packed sideways just far enough to avoid overlapping its neighbours.",
  read=["The outline is a density estimate you can count",
        "Reproducible, unlike a strip plot",
        "Every unit of width is an actual observation"],
  hides=["Nothing, until the swarm reaches the width it is allowed",
         "Past that limit it compresses or overlaps silently — roughly a few hundred per group"],
  use=["The default for showing raw values across groups at moderate n",
       "Standard in immunology and cell biology figure panels"],
  avoid=["Groups in the thousands",
         "Libraries that do not warn when the swarm overflows"],
  r="ggplot(d, aes(group, value)) + ggbeeswarm::geom_beeswarm()",
  py="seaborn.swarmplot(data=d, x='group', y='value')",
  caps=dict(shape='yes', n='yes', raw='yes', out='yes', small='yes', large='no')),

 dict(id='P321', slug='stacked-violin', name='Stacked violin plot', alias='',
  tier='niche', depth='stub',
  defn="A single-cell convention: one narrow row of violins per gene over a shared cluster axis, stacked so marker patterns read as a grid.",
  read=["Across a row: where a gene is expressed",
        "Down a column: what defines a cluster",
        "One tall violin in a row is a clean marker"],
  hides=["Absolute expression — rows are scaled independently",
         "Dropout — mass at zero mixes true absence with capture failure"],
  use=["Presenting marker genes for annotated clusters"],
  avoid=["Any claim comparing quantity between one gene and another"],
  r="Seurat::VlnPlot(obj, features = genes, stack = TRUE)",
  py="scanpy.pl.stacked_violin(adata, genes, groupby='cluster')",
  caps=dict(shape='yes', n='no', raw='no', out='no', small='no', large='yes')),

 dict(id='P322', slug='qc-violin', name='QC violin panel', alias='nFeature / nCount / percent.mt plot',
  tier='niche', depth='stub',
  defn="The standard opening figure of a single-cell analysis: genes, counts and mitochondrial fraction per cell, with candidate filter thresholds drawn on.",
  read=["Read the tail, not the bulk",
        "A long upper tail in counts suggests doublets",
        "A high mitochondrial fraction suggests dying cells",
        "The threshold lines are the decision the figure exists to support"],
  hides=["Each metric alone — cells that are only jointly anomalous stay invisible"],
  use=["Choosing and documenting QC cutoffs before filtering",
       "Pair it with counts against mitochondrial fraction"],
  avoid=["Treating defaults as universal — thresholds vary by tissue and chemistry"],
  r="Seurat::VlnPlot(obj, features = c('nFeature_RNA','nCount_RNA','percent.mt'))",
  py="scanpy.pl.violin(adata, ['n_genes_by_counts','total_counts','pct_counts_mt'])",
  caps=dict(shape='yes', n='no', raw='partial', out='yes', small='no', large='yes')),

 # ---- Shape S17, time-to-event with censoring (P234-P245) ----------
 # All eleven draw the same 800 patients; see src/survdata.py.

 dict(id='P234', slug='P234', name='Kaplan-Meier curve',
  alias='survival curve · product-limit plot', tier='universal', depth='deep',
  defn="A step estimate of the probability of surviving past each time, dropping at every event and stepping over censored patients.",
  read=["Each step down is one or more events",
        "Tick marks are censored patients, not events",
        "Height at any time is the estimated probability",
        "The right-hand tail rests on very few patients"],
  hides=["How many patients remain — the curve looks equally firm throughout",
         "Competing events, which it treats as ordinary censoring",
         "Whether censoring is related to prognosis"],
  use=["Comparing time to a single event between groups",
       "Endpoints where censoring carries no information"],
  avoid=["Endpoints where death from another cause is common",
         "Reading the far tail, where a handful of patients set the height"],
  r="survminer::ggsurvplot(survival::survfit(Surv(time, event) ~ arm, data = d))",
  py="lifelines.KaplanMeierFitter().fit(T, E).plot_survival_function()",
  caps=dict(censor='yes', atrisk='no', compete='no', ph='no', indiv='no', effect='no')),

 dict(id='P235', slug='P235', name='Number-at-risk table', alias='',
  tier='domain-signature', depth='standard',
  defn="A row of counts printed beneath a survival curve giving how many patients were still under observation at each labelled time.",
  read=["Read the count directly under the time you quote",
        "A fast-falling count means heavy censoring or many events",
        "Below about twenty, treat the curve as unreliable"],
  hides=["Why the number fell — events and censoring both reduce it",
         "Losses between the printed columns"],
  use=["Under every published Kaplan-Meier curve",
       "Wherever a late difference is being claimed"],
  avoid=["Columns so widely spaced that the depletion is hidden",
         "Printing it without the curve it annotates"],
  r="survminer::ggsurvplot(fit, risk.table = TRUE)",
  py="lifelines.plotting.add_at_risk_counts(kmf_a, kmf_b, ax=ax)",
  caps=dict(censor='partial', atrisk='yes', compete='no', ph='no', indiv='no', effect='no')),

 dict(id='P236', slug='P236', name='Cumulative incidence function plot',
  alias='competing risks CIF', tier='domain-signature', depth='deep',
  defn="The probability of having had one particular event by each time, counting events of competing types as what they are rather than as censoring.",
  read=["Height is the proportion who have had this event",
        "Curves for all causes sum to one minus overall survival",
        "It cannot exceed the proportion actually observed",
        "Set it against one minus Kaplan-Meier to see the bias"],
  hides=["The cause-specific hazard, which is what a treatment acts on",
         "That two cohorts can differ here with identical event rates"],
  use=["Any endpoint where death from another cause is possible",
       "Quoting a patient's chance of experiencing the event"],
  avoid=["Inferring a treatment effect on the event mechanism",
         "Endpoints with no genuine competing risk"],
  r="cmprsk::cuminc(ftime, fstatus, group)",
  py="lifelines.AalenJohansenFitter().fit(T, E, event_of_interest=1).plot()",
  caps=dict(censor='no', atrisk='no', compete='yes', ph='no', indiv='no', effect='no')),

 dict(id='P237', slug='P237', name='Nelson-Aalen cumulative hazard plot', alias='',
  tier='domain-signature', depth='standard',
  defn="A step estimate of the accumulated event rate, rising at each event by the reciprocal of the number still at risk.",
  read=["The slope at any point is the current hazard rate",
        "A straight line means a constant hazard",
        "It has no upper bound, unlike a probability"],
  hides=["The instantaneous hazard, which needs smoothing to see",
         "Numbers at risk, exactly as the survival curve does"],
  use=["Judging whether the event rate rises or falls over time",
       "As the quantity a Cox model is actually built on"],
  avoid=["Clinical audiences, who read probabilities not hazards",
         "The late slope, estimated from a handful of patients"],
  r="plot(survival::survfit(Surv(time, event) ~ arm), fun = 'cumhaz')",
  py="lifelines.NelsonAalenFitter().fit(T, E).plot_cumulative_hazard()",
  caps=dict(censor='yes', atrisk='no', compete='no', ph='no', indiv='no', effect='no')),

 dict(id='P238', slug='P238', name='Log-minus-log survival plot',
  alias='proportional hazards check', tier='niche', depth='stub',
  defn="Log of minus log of the survival estimate against log time — a scale on which proportional hazards makes the group curves parallel.",
  read=["Parallel curves support proportional hazards",
        "The vertical gap is the log cumulative hazard ratio",
        "Converging or crossing curves mean the ratio changes"],
  hides=["Sample size, which sets how much the curves wobble",
         "Whether the violation matters clinically"],
  use=["A quick look before fitting a Cox model",
       "Covariates with a few natural groups"],
  avoid=["Continuous covariates, which have no groups to draw",
         "Small groups, where wobble swamps the signal"],
  r="plot(survival::survfit(Surv(time, event) ~ arm), fun = 'cloglog')",
  py="matplotlib.pyplot.plot(numpy.log(t), numpy.log(-numpy.log(s)))",
  caps=dict(censor='no', atrisk='no', compete='no', ph='yes', indiv='no', effect='no')),

 dict(id='P239', slug='P239', name='Schoenfeld residual plot', alias='',
  tier='niche', depth='deep',
  defn="One residual per event, measuring how far the failing patient's covariate sat from the risk-set average, plotted against time.",
  read=["A flat smoother supports proportional hazards",
        "A sloping smoother means the effect changes with time",
        "A binary covariate puts every residual in one of two bands",
        "Read the fitted curve, not the individual points"],
  hides=["Censored patients, which contribute no residual",
         "How large the violation is in clinical terms"],
  use=["Checking a Cox model you have already fitted",
       "Deciding whether to add a time-by-covariate term"],
  avoid=["Few events, where the smoother is unstable",
         "Reading a significant test as proof the model is useless"],
  r="survminer::ggcoxzph(survival::cox.zph(fit))",
  py="lifelines.CoxPHFitter().fit(df, 'T', 'E').check_assumptions(df, show_plots=True)",
  caps=dict(censor='no', atrisk='no', compete='no', ph='yes', indiv='partial', effect='no')),

 dict(id='P240', slug='P240', name='Swimmer plot', alias='',
  tier='domain-signature', depth='deep',
  defn="One horizontal bar per patient spanning their time on study, with symbols marking response, progression, death or continuing follow-up.",
  read=["Bar length is one patient's follow-up, not an average",
        "Symbols mark what happened and when",
        "An arrow means the patient is still being followed",
        "The sort order is a choice, not a finding"],
  hides=["Any estimate — there is no summary here to quote",
         "Patients left out, if the panel is a selection"],
  use=["Small early-phase cohorts where individual courses matter",
       "Showing durable responses that a median conceals"],
  avoid=["More than about forty patients",
         "Any formal comparison between arms"],
  r="swimplot::swimmer_plot(df, id = 'pt', end = 'time')",
  py="# no dedicated package; compose matplotlib.pyplot.barh with markers",
  caps=dict(censor='yes', atrisk='no', compete='yes', ph='no', indiv='yes', effect='no')),

 dict(id='P242', slug='P242', name='Waterfall plot (best tumour response)',
  alias='RECIST waterfall', tier='niche', depth='deep',
  defn="One bar per patient giving the best change from baseline in summed target lesion diameters, sorted from worst to best.",
  read=["Each bar is one patient's best value, at any time",
        "Bars are sorted, so the x-axis carries no meaning",
        "The +20% and −30% lines are the RECIST thresholds",
        "Bar count is the analysable population, not the enrolled one"],
  hides=["When the response happened and how long it lasted",
         "Patients who progressed before a scan and have no bar",
         "The whole trajectory behind one best value"],
  use=["Showing the spread of response in a single-arm study",
       "Beside a swimmer plot, which supplies the timing"],
  avoid=["Standing in for a time-to-event analysis",
         "Studies where early dropout removes the worst responders"],
  r="ggplot(d, aes(reorder(id, -change), change)) + geom_col()",
  py="matplotlib.pyplot.bar(range(len(v)), numpy.sort(v)[::-1])",
  caps=dict(censor='no', atrisk='no', compete='no', ph='no', indiv='yes', effect='no')),

 dict(id='P243', slug='P243', name='Restricted mean survival time plot',
  alias='RMST plot', tier='niche', depth='stub',
  defn="The area under a survival curve up to a stated horizon, read as a number of months of event-free life.",
  read=["The shaded area is the estimate",
        "The horizon is a choice and must be stated",
        "The area between two curves is the treatment effect",
        "The units are time, not a ratio"],
  hides=["Everything beyond the horizon",
         "Curve shape — two different curves can share an area"],
  use=["When proportional hazards fails and a hazard ratio misleads",
       "Explaining benefit to patients in months"],
  avoid=["Horizons past the follow-up of the smaller group",
         "Choosing the horizon after seeing the result"],
  r="survRM2::rmst2(time, status, arm, tau = 36)",
  py="lifelines.utils.restricted_mean_survival_time(kmf, t=36)",
  caps=dict(censor='partial', atrisk='no', compete='no', ph='no', indiv='no', effect='yes')),

 dict(id='P244', slug='P244', name='Landmark analysis plot', alias='',
  tier='niche', depth='stub',
  defn="Survival re-estimated from a fixed later time among only the patients still event-free then, so a post-baseline grouping can be compared fairly.",
  read=["The curve restarts at one on the landmark",
        "Only patients event-free at the landmark appear",
        "Compare the restarted curves, not the originals"],
  hides=["Everything that happened before the landmark",
         "The patients who had the event first, often the sickest"],
  use=["Groups defined by something measured after baseline",
       "Avoiding the immortal time bias a naive comparison creates"],
  avoid=["Landmarks chosen after inspecting the data",
         "Cohorts where most events happen before the landmark"],
  r="survfit(Surv(time - 12, event) ~ g, data = subset(d, time > 12))",
  py="lifelines.KaplanMeierFitter().fit(T[T > 12] - 12, E[T > 12])",
  caps=dict(censor='partial', atrisk='partial', compete='no', ph='no', indiv='no', effect='no')),

 dict(id='P245', slug='P245', name='Weibull probability plot', alias='',
  tier='domain-signature', depth='deep',
  defn="Event times on a scale where a Weibull distribution falls on a straight line, so the slope estimates the shape and the intercept the scale.",
  read=["Straight means Weibull; curvature means it is not",
        "The slope is the shape parameter",
        "A shape above one means the hazard rises with time",
        "Check which estimator supplied the plotting positions"],
  hides=["Censored units, if median ranks are taken over events alone",
         "How much a small departure from straightness matters"],
  use=["Reliability work, where a parametric life model is wanted",
       "Justifying a Weibull assumption before fitting one"],
  avoid=["Heavily censored data plotted from the events alone",
         "Small samples, where ordinary scatter looks like curvature"],
  r="WeibullR::MLEw2p(x)",
  py="reliability.Probability_plotting.Weibull_probability_plot(failures=t)",
  caps=dict(censor='no', atrisk='no', compete='no', ph='no', indiv='partial', effect='yes')),

 # ---- Radiotherapy and medical physics (P813-P823) -----------------
 # Written to the full format; tiered `standard` in plots.csv because the
 # capability matrix that a `deep` entry carries is defined for shape S02
 # only, and none of these entries sit in that shape.

 dict(id='P813', slug='P813', name='Percentage depth dose curve',
  alias='PDD curve · depth dose curve · central axis depth dose',
  tier='niche', depth='standard',
  defn="Dose measured along the beam's central axis in a water phantom, expressed as a percentage of the maximum, against depth.",
  read=["Surface dose is high but not the maximum",
        "Dose peaks at d-max, then falls steeply",
        "R50, the 50% depth, sets the treatable range",
        "The low tail past the fall-off is bremsstrahlung"],
  hides=["Everything off the central axis — this is one line",
         "Field size and applicator, which shift the whole curve",
         "Tissue heterogeneity; the phantom is uniform water"],
  use=["Choosing an electron energy for a target depth",
       "Commissioning and annual beam constancy checks"],
  avoid=["Oblique incidence or a sloping patient surface",
         "Beams passing through bone or lung"],
  r="plot(depth, 100 * dose / max(dose), type = 'l', xlab = 'Depth (cm)')",
  py="matplotlib.pyplot.plot(depth, 100 * dose / dose.max())",
  caps=None),

 dict(id='P814', slug='P814', name='Isodose curve',
  alias='isodose distribution · isodose plot',
  tier='niche', depth='standard',
  defn="Contours joining points of equal dose on one plane through the beam, labelled as a percentage of the prescribed or maximum dose.",
  read=["Each line joins points at one dose level",
        "Line spacing at the field edge is the penumbra",
        "Parallel evenly spaced lines mean a flat field",
        "Contours bulging around the target show conformity"],
  hides=["The third dimension — one plane of a volume",
         "Dose between contours, which is interpolated",
         "How much tissue sits at each dose level"],
  use=["Checking field placement and penumbra on a plan",
       "Teaching how beam arrangement shapes dose"],
  avoid=["Judging organ overdose — read the DVH instead",
         "Plans whose hot spot lies off this plane"],
  r="contour(x, depth, dose, levels = c(90, 70, 50, 30, 10))",
  py="matplotlib.pyplot.contour(x, depth, dose, levels=[90, 70, 50, 30, 10])",
  caps=None),

 dict(id='P815', slug='P815', name='Dose-volume histogram', alias='DVH · cumulative DVH',
  tier='niche', depth='standard',
  defn="The fraction of a structure's volume receiving at least each dose, computed over its voxels — an inverse empirical CDF.",
  read=["Height at dose D is the volume above D",
        "A target curve should stay square, then drop",
        "An organ curve should fall as early as possible",
        "Every dose constraint is one point on this curve"],
  hides=["Where the dose sits — voxels carry no position",
         "Whether hot voxels are contiguous or scattered",
         "Dose to any named subregion of the organ"],
  use=["Checking a plan against numeric dose constraints",
       "Comparing two plans over the same structure set"],
  avoid=["Serial organs, where one contiguous hot spot decides the risk",
         "Any question about where the dose landed"],
  r="DVHmetrics::showDVH(DVHmetrics::getDVH('plan.dvh', type = 'Eclipse'))",
  py="dicompylercore.dvh.DVH.from_dicom_dvh(ds, roi_number).plot()",
  caps=None),

 dict(id='P816', slug='P816', name='Differential dose-volume histogram',
  alias='differential DVH · dDVH',
  tier='niche', depth='standard',
  defn="The density form of the dose-volume histogram: the volume of a structure falling in each dose bin rather than above it.",
  read=["Bar height is volume within that bin",
        "A tall narrow spike means uniform dose",
        "A wide spread means a heterogeneous plan",
        "Two separated peaks mean two dose regimes"],
  hides=["Bin width, which sets the apparent spread",
         "Position, exactly as the cumulative form does"],
  use=["Judging dose uniformity inside a target",
       "Spotting bimodality the cumulative curve smooths away"],
  avoid=["Reading constraints — those are written cumulatively",
         "Comparing plans binned at different widths"],
  r="DVHmetrics::showDVH(dvh, cumul = FALSE)",
  py="matplotlib.pyplot.hist(voxel_dose, bins=70, density=True)",
  caps=None),

 dict(id='P817', slug='P817', name='Radiation beam profile',
  alias='lateral dose profile · cross-plane profile · off-axis ratio curve',
  tier='niche', depth='standard',
  defn="Dose against off-axis distance at one fixed depth, measured across the field in a water phantom.",
  read=["The flat central region is the useful field",
        "The 80-20% shoulder width is the penumbra",
        "Left-right asymmetry means a steering fault",
        "The penumbra widens with measurement depth"],
  hides=["Depth — one profile is one plane",
         "The other axis; in-plane and cross-plane differ",
         "Dose outside the scanned width"],
  use=["Monthly flatness and symmetry checks",
       "Commissioning a treatment planning system"],
  avoid=["Flattening-filter-free beams judged on flatness",
         "Inferring the profile at another depth"],
  r="plot(offaxis, dose, type = 'l', xlab = 'Off-axis distance (cm)')",
  py="matplotlib.pyplot.plot(offaxis, dose)",
  caps=None),

 dict(id='P818', slug='P818', name='Bragg peak curve',
  alias='proton depth dose · particle depth dose',
  tier='niche', depth='standard',
  defn="Depth dose for a proton or heavier ion beam: a low sloping entrance plateau, a sharp distal peak, then almost nothing.",
  read=["Entrance dose is roughly a quarter of the peak",
        "Peak depth is set by the beam energy",
        "Dose past the peak falls to near zero",
        "Peak width comes from range straggling"],
  hides=["Range uncertainty — the peak is drawn as if exact",
         "Lateral scatter, which grows with depth",
         "Biological effect; this is dose, not RBE-weighted"],
  use=["Arguing why particles spare tissue beyond the target",
       "Setting against the electron or photon depth dose"],
  avoid=["Treating one peak as a treatment — targets need an SOBP",
         "Planning through heterogeneous tissue on this alone"],
  r="plot(depth, dose, type = 'l', xlab = 'Depth (cm)')",
  py="matplotlib.pyplot.plot(depth, dose)",
  caps=None),

 dict(id='P819', slug='P819', name='Spread-out Bragg peak', alias='SOBP',
  tier='niche', depth='standard',
  defn="A weighted sum of Bragg peaks at stepped energies, chosen so their overlap gives a flat dose plateau across the target depth.",
  read=["The plateau is the sum, not any one beam",
        "Faint curves beneath are the weighted components",
        "The distal edge stays as sharp as one peak",
        "Entrance dose rises with plateau width"],
  hides=["The weights, which are a planning choice",
         "Each component's contribution once summed",
         "Everything lateral to the central axis"],
  use=["Showing how a particle plan covers a target in depth",
       "Comparing entrance dose against a photon plan"],
  avoid=["Claiming particle therapy spares the entrance path",
         "Targets that move with respiration"],
  r="plot(depth, peaks %*% weights, type = 'l')",
  py="matplotlib.pyplot.plot(depth, (peaks * weights).sum(axis=1))",
  caps=None),

 dict(id='P820', slug='P820', name='Gamma index map',
  alias='gamma analysis map · gamma evaluation',
  tier='niche', depth='standard',
  defn="A per-point comparison of measured against planned dose, folding a dose-difference and a distance-to-agreement tolerance into one dimensionless number.",
  read=["Gamma at or below 1 passes",
        "Colour shows how far past tolerance a point is",
        "Failures cluster where the dose gradient is steep",
        "Always read the criterion and the dose threshold with it"],
  hides=["Which of the two criteria failed",
         "The sign of the error — hot and cold look alike",
         "Absolute dose; everything is scaled to tolerance"],
  use=["Patient-specific IMRT and VMAT quality assurance",
       "Comparing a delivered fraction against its plan"],
  avoid=["Accepting a plan on passing rate alone",
         "Low-dose regions, where the threshold drives the result"],
  r="# no CRAN implementation; gamma analysis runs in Python or vendor QA software",
  py="pymedphys.gamma(axes_ref, dose_ref, axes_eval, dose_eval, 3, 2)",
  caps=None),

 dict(id='P821', slug='P821', name='Tumour control probability curve', alias='TCP curve',
  tier='niche', depth='standard',
  defn="A fitted sigmoid giving the modelled probability that a tumour is controlled, as a function of delivered dose.",
  read=["Probability climbs over a narrow dose band",
        "D50 is the dose giving 50% control",
        "Steepness is gamma-50; steeper leaves less margin",
        "The curve is a model fit, not measured points"],
  hides=["The spread of patient radiosensitivity behind one curve",
         "Fractionation — the same total dose is not the same effect",
         "Fit uncertainty; confidence bands are usually omitted"],
  use=["Arguing the case for a dose escalation",
       "Setting beside NTCP to show the therapeutic window"],
  avoid=["Predicting the outcome for one patient",
         "Doses outside the range the model was fitted on"],
  r="plot(drc::drm(controlled ~ dose, weights = n, fct = drc::LL.2(), type = 'binomial'))",
  py="matplotlib.pyplot.plot(d, 1 / (1 + (d50 / d) ** (4 * gamma50)))",
  caps=None),

 dict(id='P822', slug='P822', name='Normal tissue complication probability curve',
  alias='NTCP curve · Lyman-Kutcher-Burman curve',
  tier='niche', depth='standard',
  defn="The fitted sigmoid probability of a named normal-tissue complication against dose, usually Lyman-Kutcher-Burman with a volume-effect parameter.",
  read=["Same sigmoid form as TCP, shifted to higher dose",
        "TD50 is the dose giving a 50% complication rate",
        "The n parameter sets serial or parallel behaviour",
        "Drawn with TCP, the gap is the therapeutic window"],
  hides=["Which complication, and how it was graded",
         "The dose distribution, reduced to one effective dose",
         "The fitted cohort's fractionation and follow-up"],
  use=["Showing what a dose escalation would cost",
       "Ranking plans that already meet every hard constraint"],
  avoid=["Comparing values fitted to different endpoints",
         "Organs whose DVH shape breaks the dose reduction"],
  r="plot(dose, pnorm((dose - td50) / (m * td50)), type = 'l')",
  py="matplotlib.pyplot.plot(dose, scipy.stats.norm.cdf((dose - td50) / (m * td50)))",
  caps=None),

 dict(id='P823', slug='P823', name='Linac output constancy chart',
  alias='machine QA chart · linac daily output chart',
  tier='niche', depth='standard',
  defn="A control chart of a linear accelerator's measured output in cGy per monitor unit, plotted each working day against tolerance and action limits.",
  read=["Each point is one morning's measurement",
        "The limits are regulatory, not computed from the data",
        "A run on one side of baseline is drift, not noise",
        "A step marks a recalibration"],
  hides=["The measurement uncertainty of the chamber itself",
         "Energy and field size — one chart covers one beam",
         "What caused a deviation"],
  use=["Daily and monthly machine QA records",
       "Evidence for regulatory inspection"],
  avoid=["Reading the limits as statistical control limits",
         "One chart standing in for several beam energies"],
  r="qcc::qcc(output, type = 'xbar.one', limits = c(0.98, 1.02))",
  py="matplotlib.pyplot.plot(day, output); matplotlib.pyplot.axhline(1.02)",
  caps=None),
]
# The capability matrix is per data shape: the columns that matter when
# choosing between box and violin are not the ones that matter when choosing
# between Kaplan-Meier and a cumulative incidence function. A shape gets a
# comparison table on its page as soon as it appears here and two or more of
# its entries carry a `caps` row.
CAPCOLS={
 'S02':[('shape','Distribution shape'),('n','Sample size'),('raw','Individual points'),
        ('out','Outliers'),('small','Honest at small n'),('large','Scales past 1000')],
 'S17':[('censor','Censoring visible'),('atrisk','Numbers at risk'),
        ('compete','Honest under competing risks'),('ph','Tests proportional hazards'),
        ('indiv','Individual patients'),('effect','Gives one effect number')],
}
